{
 "title": "fortigate_metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "devices",
    "query": {
     "query": "label_values(fortigate_interface_link_up,device)"
    }
   },
   {
    "name": "interfaces",
    "query": {
     "query": "label_values(fortigate_interface_link_up{device=~\"$devices\"},interface)"
    }
   },
   {
    "name": "sdwan_sla",
    "query": {
     "query": "label_values(fortigate_virtual_wan_latency{device=~\"$devices\"},sla)"
    }
   }
  ]
 },
 "panels": [
  { "title": "fortigate_interface_status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "rx_metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(fortigate_interface_rx_bytes{device=~\"$devices\",interface=~\"$interfaces\"}[$__rate_interval])",
     "legendFormat": "{{device}} - {{interface}}-{{ip}}"
    }
   ]
  },
  {
   "title": "tx_metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(fortigate_interface_tx_bytes{device=~\"$devices\",interface=~\"$interfaces\"}[$__rate_interval])",
     "legendFormat": "{{device}} - {{interface}}-{{ip}}"
    }
   ]
  },
  {
   "title": "sdwan_status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "fortigate_virtual_wan_status{device=~\"$devices\", sla=~\"$sdwan_sla\"}",
     "legendFormat": "{{device}} - {{sla}}-{{link}}"
    }
   ]
  },
  {
   "title": "sdwan_latency_metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "fortigate_virtual_wan_latency{device=~\"$devices\", sla=~\"$sdwan_sla\"}",
     "legendFormat": "{{device}} - {{sla}}-{{link}}"
    }
   ]
  },
  {
   "title": "sdwan_jitter_metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "fortigate_virtual_wan_jitter{device=~\"$devices\", sla=~\"$sdwan_sla\"}",
     "legendFormat": "{{device}} - {{sla}}-{{link}}"
    }
   ]
  },
  {
   "title": "sdwan_packet_loss_metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "fortigate_virtual_wan_packet_loss{device=~\"$devices\", sla=~\"$sdwan_sla\"}",
     "legendFormat": "{{device}} - {{sla}}-{{link}}"
    }
   ]
  },
  {
   "title": "system_cpu_metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "fortigate_system_cpu_current{device=~\"$devices\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "aws-fortigate-ipsec-tunnel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "ipsec_in_bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(fortigate_ipsec_in_bytes{device=\"new-farukhnagar-warehouse\"}[$__rate_interval])",
     "legendFormat": "{{device}}-{{tunnel}}"
    }
   ]
  },
  {
   "title": "ipsec_out_bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(fortigate_ipsec_out_bytes{device=\"new-farukhnagar-warehouse\"}[$__rate_interval])",
     "legendFormat": "{{device}}-{{tunnel}}"
    }
   ]
  },
  {
   "title": "ipsec_status",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "fortigate_ipsec_status{device=\"new-farukhnagar-warehouse\"}",
     "legendFormat": "{{device}}-{{tunnel}}"
    }
   ]
  }
 ]
}